server:
  port: 7777
  error:
    includeMessage: ALWAYS

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/erupt?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true
    password: root
    username: root
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    show-sql: true
  redis:
    host: localhost

erupt:
  # 是否开启csrf防御
  csrfInspect: true
  # 是否开启redis方式存储session，默认false，开启后需在配置文件中添加redis配置
  redisSession: true
  # 附件上传存储路径, 默认路径为：/opt/erupt-attachment
  #  uploadPath: /Users/Pictures
  uploadPath: C:/Users/Pictures
  # 是否保留上传文件原始名称
  keepUploadFileName: false
  # 登录session时长（redisSession为true时有效）
  upms.expireTimeByLogin: 60
  # 是否记录操作日志，默认true，该功能开启后可在【系统管理 → 操作日志】中查看操作日志
  security.recordOperateLog: true

magic-api:
  web: /magic/web
  # 接口配置文件存放路径
  resource.location: C:/erupt/magic-script/erupt-mes
