server:
  port: 7777
  error:
    includeMessage: ALWAYS

spring:
  datasource:
    url: jdbc:mysql://1.2.3.4:3306/hgmes?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true
    username: root
    password: root
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    show-sql: true
#  redis:
#    host: localhost

erupt:
  csrfInspect: true
  redisSession: false
  #  uploadPath: /Users/Pictures
  uploadPath: D:/erupt/Pictures
  keepUploadFileName: false
  upms.expireTimeByLogin: 60
  security.recordOperateLog: true

magic-api:
  web: /magic/web
  resource.location: D:/erupt/magic-script/erupt-mes
